from pathlib import Path

path = Path(r'C:/Users/Maple Razer/Desktop/trading_lab/backtest_report_viewer.html')
text = path.read_text(encoding='utf-8')

text = text.replace(
"""    input[type=\"file\"] {\n      width: 100%;\n      border: 1px dashed #3d4e45;\n      border-radius: 12px;\n      background: #101814;\n      color: var(--text);\n      padding: 10px;\n      font: inherit;\n    }\n""",
"""    input[type=\"file\"], select {\n      width: 100%;\n      border: 1px dashed #3d4e45;\n      border-radius: 12px;\n      background: #101814;\n      color: var(--text);\n      padding: 10px;\n      font: inherit;\n    }\n    select {\n      border-style: solid;\n      appearance: none;\n    }\n""")

text = text.replace(
"""          <section>\n            <h2 class=\"section-title\">1) Nạp artifact</h2>\n            <div class=\"stack\">\n              <div class=\"field\">\n                <label for=\"reportFile\">Report JSON</label>\n                <input id=\"reportFile\" type=\"file\" accept=\".json,application/json\">\n              </div>\n              <div class=\"field\">\n                <label for=\"tradesFile\">Trades CSV (optional)</label>\n                <input id=\"tradesFile\" type=\"file\" accept=\".csv,text/csv\">\n              </div>\n              <div class=\"field\">\n                <label for=\"equityFile\">Equity Curve CSV (optional)</label>\n                <input id=\"equityFile\" type=\"file\" accept=\".csv,text/csv\">\n              </div>\n              <div class=\"field\">\n                <label for=\"bundleFiles\">Hoặc chọn 3 file cùng lúc (optional)</label>\n                <input id=\"bundleFiles\" type=\"file\" accept=\".json,.csv\" multiple>\n              </div>\n            </div>\n          </section>\n\n          <section>\n            <h2 class=\"section-title\">2) Hành động</h2>\n            <div class=\"stack\">\n              <button id=\"loadSampleBtn\" type=\"button\">Load sample run hiện có</button>\n              <button id=\"resetBtn\" type=\"button\" class=\"secondary\">Reset viewer</button>\n            </div>\n          </section>\n\n          <section>\n            <h2 class=\"section-title\">3) Trạng thái</h2>\n            <div id=\"statusLine\" class=\"status-line\">Chưa có report nào được nạp.</div>\n          </section>\n\n          <section>\n            <h2 class=\"section-title\">4) Cách dùng</h2>\n""",
"""          <section>\n            <h2 class=\"section-title\">1) Chọn run từ outputs</h2>\n            <div class=\"stack\">\n              <div class=\"field\">\n                <label for=\"runSelect\">Backtest runs (mới nhất ở trên)</label>\n                <select id=\"runSelect\">\n                  <option value=\"\">-- đang tải manifest --</option>\n                </select>\n              </div>\n              <div class=\"small\" id=\"manifestMeta\">Manifest chưa nạp.</div>\n            </div>\n          </section>\n\n          <section>\n            <h2 class=\"section-title\">2) Nạp artifact thủ công (fallback)</h2>\n            <div class=\"stack\">\n              <div class=\"field\">\n                <label for=\"reportFile\">Report JSON</label>\n                <input id=\"reportFile\" type=\"file\" accept=\".json,application/json\">\n              </div>\n              <div class=\"field\">\n                <label for=\"tradesFile\">Trades CSV (optional)</label>\n                <input id=\"tradesFile\" type=\"file\" accept=\".csv,text/csv\">\n              </div>\n              <div class=\"field\">\n                <label for=\"equityFile\">Equity Curve CSV (optional)</label>\n                <input id=\"equityFile\" type=\"file\" accept=\".csv,text/csv\">\n              </div>\n              <div class=\"field\">\n                <label for=\"bundleFiles\">Hoặc chọn 3 file cùng lúc (optional)</label>\n                <input id=\"bundleFiles\" type=\"file\" accept=\".json,.csv\" multiple>\n              </div>\n            </div>\n          </section>\n\n          <section>\n            <h2 class=\"section-title\">3) Hành động</h2>\n            <div class=\"stack\">\n              <button id=\"loadLatestBtn\" type=\"button\">Load run mới nhất</button>\n              <button id=\"resetBtn\" type=\"button\" class=\"secondary\">Reset viewer</button>\n            </div>\n          </section>\n\n          <section>\n            <h2 class=\"section-title\">4) Trạng thái</h2>\n            <div id=\"statusLine\" class=\"status-line\">Chưa có report nào được nạp.</div>\n          </section>\n\n          <section>\n            <h2 class=\"section-title\">5) Cách dùng</h2>\n""")

text = text.replace(
"""  <script>\n    const state = {\n""",
"""  <script src=\"./backtest_report_manifest.js\"></script>\n  <script>\n    const manifest = window.BACKTEST_REPORT_MANIFEST || { runs: [], count: 0 };\n\n    const state = {\n""")

text = text.replace(
"""      loadedFiles: { report: null, trades: null, equity: null },\n    };\n\n    const samplePaths = {\n      report: 'C:/Users/Maple Razer/outputs/reports/3c379abec237ab1f.json',\n      trades: 'C:/Users/Maple Razer/outputs/backtests/3c379abec237ab1f/trades.csv',\n      equity: 'C:/Users/Maple Razer/outputs/backtests/3c379abec237ab1f/equity_curve.csv',\n    };\n""",
"""      loadedFiles: { report: null, trades: null, equity: null },\n      activeRunId: null,\n    };\n""")

text = text.replace(
"""    function renderAll() {\n      renderHero();\n      renderMetrics();\n      renderContractAndSignals();\n      renderEquity();\n      renderMonthly();\n    }\n\n    function resetViewer() {\n""",
"""    function renderAll() {\n      renderHero();\n      renderMetrics();\n      renderContractAndSignals();\n      renderEquity();\n      renderMonthly();\n    }\n\n    function populateRunSelect() {\n      const select = $('runSelect');\n      const meta = $('manifestMeta');\n      if (!select || !meta) return;\n      const runs = Array.isArray(manifest.runs) ? manifest.runs : [];\n      if (!runs.length) {\n        select.innerHTML = '<option value="">-- không có run nào trong manifest --</option>';\n        meta.textContent = 'Manifest rỗng hoặc chưa build.';\n        return;\n      }\n      select.innerHTML = ['<option value="">-- chọn một run --</option>'].concat(runs.map((run, idx) => `<option value="${esc(run.run_id)}">${esc(run.label || run.run_id)}</option>`)).join('');\n      meta.textContent = `Manifest: ${manifest.count} run · generated ${manifest.generated_at || 'unknown'} · root ${manifest.root_outputs || ''}`;\n    }\n\n    function loadRunFromManifest(runId) {\n      const run = (manifest.runs || []).find((item) => item.run_id === runId);\n      if (!run) {\n        setStatus(`Không tìm thấy run ${runId} trong manifest.`);\n        return;\n      }\n      state.activeRunId = run.run_id;\n      state.report = {\n        strategy_name: run.strategy_name,\n        dataset_id: run.dataset_id,\n        feature_set_id: run.feature_set_id,\n        config_hash: 'manifest',\n        backtest_config: run.backtest_config || {},\n        metrics_summary: run.metrics_summary || {},\n        validation_results: run.validation_results || {},\n        signal_counts: run.signal_counts || {},\n        artifacts: {\n          trade_log_path: run.trades_file,\n          equity_curve_path: run.equity_file,\n          report_path: run.report_file,\n        },\n      };\n      state.trades = Array.isArray(run.trade_sample) ? run.trade_sample : [];\n      state.equity = Array.isArray(run.equity_sample) ? run.equity_sample : [];\n      state.monthly = Array.isArray(run.monthly) ? run.monthly : [];\n      state.selectedMonth = state.monthly[state.monthly.length - 1]?.month || null;\n      state.loadedFiles = {\n        report: run.report_file || run.run_id,\n        trades: run.trades_file || null,\n        equity: run.equity_file || null,\n      };\n      setStatus([\n        `Loaded from manifest: ${run.run_id}`,\n        `strategy: ${run.strategy_name || 'unknown'}`,\n        `modified_at: ${run.modified_at || 'unknown'}`,\n        `trade_rows: ${run.trade_rows ?? '—'} · equity_rows: ${run.equity_rows ?? '—'}`,\n        'Sorted newest → oldest from outputs folder.'\n      ]);\n      renderAll();\n    }\n\n    function resetViewer() {\n""")

text = text.replace(
"""      state.loadedFiles = { report: null, trades: null, equity: null };\n      ['reportFile','tradesFile','equityFile','bundleFiles'].forEach((id) => { const el = $(id); if (el) el.value = ''; });\n      setStatus('Chưa có report nào được nạp.');\n      renderAll();\n    }\n""",
"""      state.loadedFiles = { report: null, trades: null, equity: null };\n      state.activeRunId = null;\n      ['reportFile','tradesFile','equityFile','bundleFiles'].forEach((id) => { const el = $(id); if (el) el.value = ''; });\n      if ($('runSelect')) $('runSelect').value = '';\n      setStatus('Chưa có report nào được nạp.');\n      renderAll();\n    }\n""")

text = text.replace(
"""    $('resetBtn').addEventListener('click', resetViewer);\n\n    $('loadSampleBtn').addEventListener('click', async () => {\n      setStatus([\n        'Sample mode note:',\n        `report path expected: ${samplePaths.report}`,\n        `trades path expected: ${samplePaths.trades}`,\n        `equity path expected: ${samplePaths.equity}`,\n        'Do browser security, sample mode chỉ là nhắc đường dẫn. Hãy dùng file picker để nạp thật các file này.'\n      ]);\n    });\n\n    renderAll();\n""",
"""    $('resetBtn').addEventListener('click', resetViewer);\n\n    if ($('runSelect')) {\n      $('runSelect').addEventListener('change', (e) => {\n        if (!e.target.value) return;\n        loadRunFromManifest(e.target.value);\n      });\n    }\n\n    if ($('loadLatestBtn')) {\n      $('loadLatestBtn').addEventListener('click', () => {\n        const latest = (manifest.runs || [])[0];\n        if (!latest) {\n          setStatus('Manifest chưa có run nào để load.');\n          return;\n        }\n        if ($('runSelect')) $('runSelect').value = latest.run_id;\n        loadRunFromManifest(latest.run_id);\n      });\n    }\n\n    populateRunSelect();\n    renderAll();\n""")

path.write_text(text, encoding='utf-8')
print('updated viewer')
